version: '3'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:5000
      - NEXTAUTH_URL=http://localhost:3000
      - NEXTAUTH_SECRET=rwabridge-next-auth-secret
    depends_on:
      - backend
    networks:
      - rwabridge-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - MONGO_URI=mongodb://mongo:27017/rwabridge
      - JWT_SECRET=rwabridge-jwt-secret-key
      - JWT_LIFETIME=30d
    depends_on:
      - mongo
    networks:
      - rwabridge-network

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - rwabridge-network

networks:
  rwabridge-network:
    driver: bridge

volumes:
  mongo-data:
